name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: "the name of the AWS bucket"
    required: true
  bucket-region:
    description: "The region of the S3 bucket"
    required: false
    default: 'us-east-1'
  dist-folder:
    description: "The folder containing the deployable files"
    required: true
outputs:    
  bucket-url:
    description: "the url of the deploied bucket"
runs: 
  using: 'node16' # it's telling github that we are using a js action because  is a js runtime
  main: 'main.js' # define the file that we specify
