name: "chached deps"
description: "Install and cache dependencies"
inputs:
  cached: 
    description: "If false no cache at all"
    required: false
    default: "true"
runs: 
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: inputs.cached == 'true' && steps.cache.outputs.cache-hit != 'true' 
      run: npm ci
      shell: bash
